#define FPS 80
#define ALIEN_BULLET_SPEED 8
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define PLAYER_SPEED 4
#define PLAYER_BULLET_SPEED 16
#define SIDE_PLAYER 0
#define SIDE_ENEMY 1
#define MAX_KEYBOARD_KEYS 350
#define MAX_STARS 250
#define MAX_SND_CHANNELS 8
#define MAX_LINE_LENGTH 40
#define NUM_HIGHSCORES 8
#define STRNCPY(dest, src, n) strncpy(dest, src, n); dest[n - 1] = '\0'
#define GLYPH_HEIGHT 28
#define GLYPH_WIDTH 18
#define MAX_NAME_LENGTH 32
#define MAX_SCORE_NAME_LENGTH 16
#define MAX_RANK 7
#define SND_MAX 10
#define METEOR_SPEED 10
#define MISSILE_SPEED 12
#define CH_ANY 0
#define CH_PLAYER 1
#define CH_ALIEN_FIRE 2
#define CH_MENU 3
#define CH_BUTTON 4
#define CH_POINTS 5
#define SND_PLAYER_FIRE 0
#define SND_ALIEN_FIRE 1
#define SND_PLAYER_DIE 2
#define SND_ALIEN_DIE 3
#define SND_MENU 4
#define SND_BUTTON 5
#define SND_POINTS 6
#define TEXT_LEFT 0
#define TEXT_CENTER 1
#define TEXT_RIGHT 2
